# NUMPY
NumPy (Numerical Python) is a powerful open-source Python library used for working with numerical data. It provides support for multi-dimensional arrays (like vectors, matrices, and tensors) and tools to perform mathematical operations on them efficiently


In [2]:
# importing  libraries
import numpy as np

# Numpyarrray
A NumPy array (also called ndarray) is a grid of values (like numbers), all of the same type, and is indexed by a tuple of non-negative integers

In [4]:
# creating an empty list
narray = np.array([])
print(type(narray))
print(len(narray))

<class 'numpy.ndarray'>
0


In [5]:
narray

array([], dtype=float64)

In [6]:
# other way to crerat a empty ndarray
nan = np.array(object = None)# only exceptioon where  length is none
print(type(nan))

<class 'numpy.ndarray'>


In [7]:
nan

array(None, dtype=object)

In [8]:
# creating narray using list
some_list = [1,2,3,4]

In [9]:
n_list = np.array(object = some_list)

In [10]:
n_list.dtype

dtype('int32')

In [11]:
type(n_list)

numpy.ndarray

In [12]:
# can also store str in ndarray
n_arrr = np.array(["sanjay", "Abhi"])
type(n_arrr)

numpy.ndarray

In [13]:
n_type = np.array(object = [1,2,3,], dtype = int)

In [14]:
n_type1 = np.array(object = [1,2,3,], dtype = float)

In [15]:
n_same = nparray([1,2.2,3]) # all the element inside the array shoul be same dtype

NameError: name 'nparray' is not defined

In [ ]:
# interger will be converted to string
n_sd = np.array(["sanjay",3.4, "Abhi", '8\9'])
n_sd

In [ ]:
# creating narray using tuple
n_t = (-1, 5,5,)
print(n_t, type(n_t))

In [ ]:
n_t_a = np.array(n_t)
print(n_t_a, type(n_t_a))

## creating a  ndarray using the set


In [ ]:
seta = {'a',5.5,"sanjay"}
type(seta)

In [ ]:
seta[0]

In [ ]:
seta_na = np.array(seta)
print(seta_na, type(seta_na))

In [ ]:
seta_na[1] # still not indexable

In [ ]:
## from a misxtd list m

In [ ]:
mixed_list = [['sanjay'], 1.2, 2, "abhi"]

In [ ]:
type(mixed_list[2])

In [ ]:
nda = np.array(mixed_list, )

In [ ]:
nda = np.array(mixed_list, dtype = object )

In [ ]:
# define a function to tt returns even number 
def even_numbers(n): return np.array([2*i for i in range(n)])

In [ ]:
even_numbers(2222)

## creating a 2d array

In [ ]:
tow_d= np.array([[1,2,3], [4,5,6]])
print(tow_d)

In [ ]:
import numpy as np

array_3d = np.array([[[ (i, j, k) for k in range(3)] for j in range(3)] for i in range(3)])
array_3d

 # Numpy array Attributes

In [ ]:
n_arry =np.array([[1,-1],[0,1]])
n_arry

In [ ]:
n_arry.ndim # give the dimension

In [ ]:
n_arry.shape # shape give number of in=tems if u loook in a certain angle

In [ ]:
len(n_arry.shape)

## Acessing element in 1d array

In [17]:
np_arr = np.array([12,32,-43,22,78,-98])
np_arr

array([ 12,  32, -43,  22,  78, -98])

In [21]:
np_arr.ndim

1

In [23]:
np_arr.shape

(6,)

In [25]:
len(np_arr)

6

In [27]:
np_arr[2]

-43

In [31]:
np_arr[1:3]

array([ 32, -43])

In [35]:
np_arr[5:len(np_arr)]

array([-98])

In [41]:
np_arr[[0]]

array([12])

In [43]:
np_arr[:-1]

array([ 12,  32, -43,  22,  78])

In [45]:
np_arr[-1]

-98

In [47]:
# reversing  the np array
np_arr[::-1]

array([-98,  78,  22, -43,  32,  12])

## accesing the elements in 2d array

In [50]:
npa = np.array([[1,2,3],[4,5,6]])
npa

array([[1, 2, 3],
       [4, 5, 6]])