In [9]:
# subscripting
#pulling a element out of the string is called subscripting
print('hello'[0])# tts subscripting

h


# Type Converstion

In [6]:
# string to int
x = '31' # anything inside the qutes aarw string
y = int(x)
print("The data type of the variabel y is :",type(y))

The data type of the variabel y is : <class 'int'>


In [8]:
x = "42.5"
y = int(x)


ValueError: invalid literal for int() with base 10: '42.5'

In [10]:
bool(0)
bool(5)


True

In [14]:
x = 5
y = complex(x)
print('Type of y is ',type(y))

Type of y is  <class 'complex'>


In [16]:
y

(5+0j)

In [22]:
# convertng a number to str
x = 3.14
y = str(x)
print("The type of y will br:",type(y))
print(y) # here 3,14 is converted to str

The type of y will br: <class 'str'>
3.14


In [24]:
t = float(y)
t

3.14

In [28]:
u = 'abc'
r = list(u)
r

['a', 'b', 'c']

In [32]:
x = ['a', 'b', 'c']
y = str(x)
y

"['a', 'b', 'c']"

In [34]:
# To combine all the characters in a list into one string, we use the "".join() method.
x = ['a', 'b', 'c']
y = ''.join(x)
y

'abc'

In [42]:
x = (1, 2, 3)
y = list(x)
y

[1, 2, 3]

In [44]:
# list to tuple
x = [1, 2, 3]
y = tuple(x)
y

(1, 2, 3)

In [50]:
# to set
x = (1, 2, 2, 3)
y = set(x)
y # duplicates have been remove

{1, 2, 3}

In [52]:
# dict to list
x = {'a': 1, 'b': 2, 'c': 3}
y = list(x)
y

['a', 'b', 'c']

In [54]:
x = [('a', 1), ('b', 2), ('c', 3)]
y = dict(x)
y

{'a': 1, 'b': 2, 'c': 3}

In [56]:
x = [1, 2, 3]
y = dict(x)
y

TypeError: cannot convert dictionary update sequence element #0 to a sequence

In [58]:
x = {1, 2, 3}
y = dict.fromkeys(x, "hi")
y

{1: 'hi', 2: 'hi', 3: 'hi'}

In [62]:
x = {'a': 1, 'b': 2}
y = tuple(x)
y


('a', 'b')

In [64]:
x = [("x", 9), ("y", 10)]
y = dict(x)
y

{'x': 9, 'y': 10}

# Numpy converstion


In [71]:
import numpy as np
arr = np.array([1, 2, 3])
y = arr.astype(float)
print(y)
print("The type of y will be :",type(y))

[1. 2. 3.]
The type of y will be : <class 'numpy.ndarray'>


In [73]:
arr = np.array([1.7, 2.9, 3.1])
y = arr.astype(int) # When you do astype(int) on a float array, NumPy simply truncates (drops) the decimals — it doesn’t round.
print(y)


[1 2 3]


In [77]:
arr = np.array(["1", "2", "3"])
y = arr.astype(int)
y

array([1, 2, 3])

In [79]:
arr = np.array(["1", "two", "3"])
y = arr.astype(int)


ValueError: invalid literal for int() with base 10: 'two'

In [83]:
arr = np.array([1, 2, 3])
y = arr.astype(bool)
print(y) # Every nonzero number becomes True, so [1, 2, 3] → [True, True, True].

[ True  True  True]


In [87]:
import numpy as np
arr = np.array([1, 2.5, 3]) # can’t mix int and float, it promotes them to the “wider” type.
print(type(arr))

<class 'numpy.ndarray'>


In [93]:
arr = np.array([1, "2", 3]) # here np will convert every thing into str but the dtype will shoe np.array
type(arr)

numpy.ndarray

# Type converstion in Pandas 

In [98]:
import pandas as pd
df = pd.DataFrame({
    'A': ['1', '2', '3'],
    'B': [1.5, 2.5, 3.5]
})
df['A'] = df['A'].astype(int)
print(type(df['A']))

<class 'pandas.core.series.Series'>


In [100]:
# Other ways to change dtypes:
df['A'] = pd.to_numeric(df['A'])


In [106]:
# to data and time
# df['date'] = pd.to_datetime(df['date'])


pd.to_timedelta()

Converts strings like '5 days' into timedelta values.

pd.to_numeric(df[col], downcast='integer')

Converts while using the smallest possible dtype.

convert_dtypes() (newer)

df = df.convert_dtypes()

Auto-detects better dtypes for all columns.